### ISSUE TITLE
Add activity logging?

### ISSUE THREAD

**Issue by rpruim** [Energy-Visualizer/eviz#33] opened 2024-06-19 14:31 UTC
I'm wondering if we want to add some activity logging to the site.  We'd have to decide the granularity of the logging, but especially if we seek outside funding to keep the site going, it could be good if we can demonstrate how the site is being used.

Some types of things that could be logged:

* [x] account creation
* [x] logins
* [x] plot generation (either that it happened, or which data were used)
* [x] data downloads (either that it happened or which data were downloaded)
* [x] visits to other pages on the site
* [x] adds of IEA data (and whether this happened at the time of account creation or later)

Access to this information could be part of the administration part of the website.

**Comment by kenny5033** [comment] 2024-06-19 17:49
[Django provides a logging framework](https://docs.djangoproject.com/en/5.0/ref/logging/#django-logger) with extensible output options (flat file, email, etc.)

I don't see an easy "flip the switch" option for navigation logging, but we could log which user visited which page whenever a page is loaded and track their navigation.

**Comment by kenny5033** [comment] 2024-07-12 16:42
Logging system is now being used with the following example showing the current format. The messages are saved to a log file.

[2024-07-12 16:38:55,074] INFO (File:views.py Function:get_plot Line:79) Sankey plot made

**Comment by kenny5033** [comment] 2024-07-31 15:09
When an admin makes IEA permission changes via the admin page, these messages will be put in the log file, respectively:

[2024-07-31 15:05:26,854] INFO (File:admin.py Function:allow_iea Line:30) User ******** granted IEA permissions
[2024-07-31 15:05:38,160] INFO (File:admin.py Function:remove_iea Line:52) User ******** IEA permissions revoked

Where ******** would be the user's name. For batch adding / revoking user permissions, each user is given their own line.

This has been testing and works as intended. Closing accordingly.

**Closed by kenny5033** 2024-07-31 15:09 UTC
Labels: enhancement
